@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedMentorstack" as VersionedMentorstack MODEL_COLOR
end box

[-> Model : undoMentorstack()
activate Model

Model -> VersionedMentorstack : undo()
activate VersionedMentorstack

VersionedMentorstack -> VersionedMentorstack :resetData(ReadOnlyMentorstack)
VersionedMentorstack --> Model :
deactivate VersionedMentorstack

[<-- Model
deactivate Model

@enduml
